name: Rust & pnpm Test

on:
  push:
    branches: [ main, beta ]
  pull_request:
    branches: [ main, beta ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v3
        with:
          version: 8
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
      - name: Install Rust dependencies
        run: sudo apt-get update && sudo apt-get install -y pkg-config libssl-dev
      - name: Install pnpm dependencies
        run: pnpm install
      - name: Run Rust tests via pnpm
        run: pnpm run test

